---
dependencies:
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
description: "'A pkg in Coin Galaxy.'"
dev_dependencies:
  auto_exporter: ^4.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  test: ^1.24.0
  very_good_analysis: any
environment:
  sdk: ^3.0.0
name: finance_kline_core
homepage: https://github.com/normidar/finance_kline_core
topics:
  - a
  - b
  - c
  - d
  - e
version: 0.0.1
